var bass1= document.getElementById(botton1)
var bass1_sound= document.getElementById("bass1-sound")
bass1.addEventListener('click',function(){
    console.log('it was clicked')
    bass1_sound.play()
})
var bass2= document.getElementById(botton2)
var bass2_sound= document.getElementById("bass2-sound")
var bass3= document.getElementById(botton3)
var bass3_sound= document.getElementById("bass3-sound")
var bass4= document.getElementById(botton4)
var bass4_sound= document.getElementById("bass4-sound")
var snare1= document.getElementById(botton5)
var snare1_sound= document.getElementById("snare1-sound")
var snare2= document.getElementById(botton6)
var snare2_sound= document.getElementById("snare2-sound")
var snare3= document.getElementById(botton7)
var snare3_sound= document.getElementById("snare3-sound")
var snare4= document.getElementById(botton8)
var snare4_sound= document.getElementById("snare4-sound")